version: '3'
services:
  frontend:
    container_name: container-frontend-notas
    build: ./front-end
    ports:
      - '3000:3000'
    networks:
      - net
    depends_on:
      - app
  app:
    container_name: container-app-notas
    build: ./back-end
    ports:
      - '8081:8081'
    networks:
      - net
    depends_on:
      - db
  db:
    container_name: container-db-notas
    image: 'mysql:8.0'
    environment:
      MYSQL_DATABASE: AppNotas
      MYSQL_USER: user-app
      MYSQL_ROOT_PASSWORD: '!uWzy&c00!s5'
      MYSQL_PASSWORD: '!uWzy&c00!s5'
    ports:
      - '3306:3306'
    volumes:
      - './database/data:/var/lib/mysql'
      - './database/startup-scripts:/docker-entrypoint-initdb.d/init-script.sql'
    networks:
      - net
networks: 
  net: